### ISSUE TITLE
https://brandenburg.social

### ISSUE THREAD

**Issue by soletan** [jazmichaelking/mastodon-near-me#1]
This is kind of counterpart to existing https://berlin.social addressing people living in Germany's federal state surrounding Berlin and any topic related to this state. The state's capital might be a good place to put the pin, which is [Potsdam](https://umap.openstreetmap.fr/en/map/mastodon-near-me_550053#18/52.39730/13.05340) ...

**Comment by jazmichaelking** [comment]
Thank you for adding the link! 

https://brandenburg.social has been added to the map, To avoid complications, only the OpenStreetmap names are used, so markers are located in the geographic centre of the Brandenburg State polygon. As this is for a region and not a city, the region marker is used; city servers get the pin in the city itself.

**Comment by soletan** [comment]
I see. Sounds eligible.
