### ISSUE TITLE
Adding another Alaska (United States) regional server

### ISSUE THREAD

**Issue by Yekrats** [jazmichaelking/mastodon-near-me#100]
Hi there -

I just found that there is another regional Alaska server at https://alaskan.social/about

Hope this helps,
-- Scott S. [@ScottStarkey@hoosier.social](https://hoosier.social/@ScottStarkey)

**Comment by jazmichaelking** [comment]
It was on the map, but missing from the data, so I've updated the directory and confirmed the map placement. Cheers!
