### ISSUE TITLE
https://social.anufrij.de

### ISSUE THREAD

**Issue by artemanufrij** [jazmichaelking/mastodon-near-me#14]
Germany, Bavaria, Fuerth

**Comment by jazmichaelking** [comment]
OSM is not showing me a Feurth, can you give me lat long?

**Comment by pagiraud** [comment]
It is showing me the town: I think you mispelled it. It’s Fuerth, not Feurth. Position : https://www.openstreetmap.org/#map=12/49.4768/10.9884

**Comment by artemanufrij** [comment]
https://www.openstreetmap.org/#map=14/49.4774/10.9895

**Comment by jazmichaelking** [comment]
Got it. This service is currently not accepting registrations, so will not be included - please see inclusion criteria

**Comment by artemanufrij** [comment]
Why not include both types of instances. One with "open" :unlock:  icon and other one with "close" :lock:

**Comment by artemanufrij** [comment]
So you could see the whole fediversum :smile:

**Comment by jazmichaelking** [comment]
The purpose of the map ios to help new potential members figure out which server to join. Servers that are not open for registration don't help in this case

**Comment by artemanufrij** [comment]
I understand your point. Thanks for feedback :+1:
