### ISSUE TITLE
digitalcourage.social

### ISSUE THREAD

**Issue by pietsch** [jazmichaelking/mastodon-near-me#26]
digitalcourage.social is a predominantly German-speaking Mastodon instance run by Digitalcourage e.V. which is based in Bielefeld, NRW, Germany. Its scope is Germany.

**Comment by jazmichaelking** [comment]
Hi, could you update the server description to be in German, and please clarify if it is actually 1 Euro per month to join, thanks.

**Comment by pietsch** [comment]
The server description is already shown in German. Is your web browser configured to ask for a different language?

Payment is mentioned here: https://digitalcourage.social/about/more

Mastodon does not have a configuration option that allows us to put these details on https://digitalcourage.social/about as far as I know.

**Comment by jazmichaelking** [comment]
On https://digitalcourage.social/about the server description is still the default English text. Please update to German, and clearly describe that you are a regional server for Germany (this is a region-based directory). Is the 1 Euro fee optional?

**Comment by pietsch** [comment]
You did not understand what I wrote previously. If configure your browser to prefer German content, you will get German content. This is achieved by a process called content negotiation. Do you use the LibreWolf browser? It might always request English in order to blend in.

The 1 Euro fee is not optional because paying for the server is not optional. Do you prefer Mastodon instances that die quickly?

**Comment by jazmichaelking** [comment]
Hi Pietsch, thanks for your comments. This project is for newcomer onboarding to region-focussed servers. As such, we are looking to list local servers with no fees, so we will not be including this server in the directory. This is not intended to be an exhaustive, authoritative list, merely a stepping stone to get the less savvy folks into a server near them. Best of luck with your instance!
