### ISSUE TITLE
Servers based in Italy 

### ISSUE THREAD

**Issue by Mannivu** [jazmichaelking/mastodon-near-me#36]
I suggest the addition of two more server based in Italy: https://livellosegreto.it and https://sociale.network.

**Comment by jazmichaelking** [comment]
For inclusion, the server description on /about must describe that the server is primarily for a specific area, region, country, or language. Both of these appear to be generalistic servers. This map is not intended for all servers to be listed based on where they are located. It is for servers describing themselves as serving a particular area.
