### ISSUE TITLE
Add https://inosoft.social

### ISSUE THREAD

**Issue by HerrBausM** [jazmichaelking/mastodon-near-me#38]
Hi, we are hosting [inosoft.social](https://inosoft.social), a mastodon server located in Marburg, Hessen, Germany. Open for registration, approval needed though.

Pin: https://www.openstreetmap.org/relation/225494#map=19/50.78692/8.76244

**Comment by jazmichaelking** [comment]
Please review your server information at https://inosoft.social/about/more (there is none)

**Comment by HerrBausM** [comment]
Updated.

**Comment by jazmichaelking** [comment]
This appears to be a general server, not region specific, please describe the specific region you are soliciting users from
