### ISSUE TITLE
Add Instances from Austria

### ISSUE THREAD

**Issue by anreiterAT** [jazmichaelking/mastodon-near-me#39]
Hello,

please add this instances:

**Austria:**
aut.social
fedi.at
literatur.social
mastodon.party.at

**Krems in Austria:**
krems.social

**Linz in Austria:**
ooe.social

**Kitzbühel in Austria:**
tyrol.social

Thank you!

Regards,
Bernhard

**Comment by jazmichaelking** [comment]
added aut.social, fedi.at, ooe.social, tyrol.social
