### ISSUE TITLE
Add uksocial.cloud

### ISSUE THREAD

**Issue by fov151** [jazmichaelking/mastodon-near-me#40]
Please add uksocial.cloud.
A uk focused instance
Suggested pin 53.3807 -1.4702 (the city where the admin resides)
Thanks

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
