### ISSUE TITLE
https://verkehrswende.social/

### ISSUE THREAD

**Issue by larsschwarz** [jazmichaelking/mastodon-near-me#42]
(Mostly German speaking) instance for new sustainable urban mobility
Suggested pin 53.1441014, 8.1506947 (the city where the admin resides)
Thanks

**Comment by jazmichaelking** [comment]
Please describe the specific region you are soliciting membership from.

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation
