### ISSUE TITLE
https://bvb.social

### ISSUE THREAD

**Issue by gerdemann** [jazmichaelking/mastodon-near-me#43]
An instance for BVB Fans. A possible location for the Pin might be 51.49256, 7.45248

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
