### ISSUE TITLE
Please add digisociety.social

### ISSUE THREAD

**Issue by rgiersig** [jazmichaelking/mastodon-near-me#44]
The Digital Society is an NGO that aims at a fair, free, safe and sustainable society, whose members may share the benefits of the digital transformation. We provide a Mastodon instance at https://digisociety.social for anyone to join. Our region is Austria, our physical location is  48.208955670902775, 16.368568627717146. 
Thank you for providing this service.

**Comment by jazmichaelking** [comment]
Not a regional server, not adding, please consider other directories
