### ISSUE TITLE
Please add douzepoints.social

### ISSUE THREAD

**Issue by MedPlexNi** [jazmichaelking/mastodon-near-me#46]
Hey,
we are a still small Mastodon server for all fans of the Eurovision Song Contest and related topics.
We are looking for more members for our community! :D

Url: https://douzepoints.social
Geo-Target: Karlsruhe, Germany
Language Focus: English

The specified inclusion criteria are all met.

**Comment by jazmichaelking** [comment]
Could you define if your server is supporting a specific geographic area, it appears to be topic (Eurovision Song Contest) based.

**Comment by MedPlexNi** [comment]
It is mainly for Europe, but Germany, Karlsruhe is also okay

**Comment by jazmichaelking** [comment]
To be included your server has to be focussed on serving the people in a  specific place
