### ISSUE TITLE
Add pfalz.social

### ISSUE THREAD

**Issue by pfalzsocial** [jazmichaelking/mastodon-near-me#47]
Hi,

please add pfalz.social, vaguely serving the German "Pfalz" area.
A good center point might be [49.343, 8.0763](https://www.openstreetmap.org/#map=10/49.343/8.0763).

Danke!

**Comment by pfalzsocial** [comment]
Ah, language: German

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation
