### ISSUE TITLE
Add kiel.social

### ISSUE THREAD

**Issue by kaffeeringe** [jazmichaelking/mastodon-near-me#48]
[mastodon.kiel.social](https://mastodon.kiel.social/) - Kiel, Germany

**Comment by jazmichaelking** [comment]
unreachable

**Comment by kaffeeringe** [comment]
Works for me.

**Comment by jazmichaelking** [comment]
![image](https://user-images.githubusercontent.com/3419832/205101867-c34ebd99-b992-4a15-b2b7-cf40989f3557.png)

**Comment by jazmichaelking** [comment]
![image](https://user-images.githubusercontent.com/3419832/205101971-49156d53-e491-43af-9f2b-ea9ac812974b.png)
