### ISSUE TITLE
Change location of norden.social

### ISSUE THREAD

**Issue by BennyBolivar** [jazmichaelking/mastodon-near-me#51]
Hey there, we are an instance founded in bremen and both founders (me and my co-founder) live in Bremen, not Hamburg. Maybe you could change our location. Would be nice. Thanks @benny@norden.social

**Comment by BennyBolivar** [comment]
@jazmichaelking it seems we are in hamburg? Maybe you can change our location back to bremen?

**Comment by jazmichaelking** [comment]
Please make sure you're using the current version of the map, there is a backup copy floating about that cannot be deleted http://mastodon-near.me 
![image](https://user-images.githubusercontent.com/3419832/215489392-a6503dca-b4a5-492b-8a60-e7efbd165b72.png)

**Comment by BennyBolivar** [comment]
Ah i see. Thanks again!
