### ISSUE TITLE
Add meckpom.social

### ISSUE THREAD

**Issue by noordjonge** [jazmichaelking/mastodon-near-me#52]
[meckpom.social](https://meckpom.social/) 

Geo: Malchow, Mecklenburg-Vorpommern, Germany
Language Focus: German
GeoLoc: 53° 28' 29.17" N, 12° 25' 19.56" E

The specified inclusion criteria are all met.

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
