### ISSUE TITLE
Add northeast.one

### ISSUE THREAD

**Issue by jsailo** [jazmichaelking/mastodon-near-me#53]
URL: https://northeast.one
Geo-Target: NorthEast India - specific to the states of Arunachal Pradesh, Assam, Manipur, Meghalaya, Mizoram, Nagaland, Tripura and Sikkim in India
Language Focus: English

The specified inclusion criteria are all met.

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
