### ISSUE TITLE
Please add odenwald.social

### ISSUE THREAD

**Issue by sthierolf** [jazmichaelking/mastodon-near-me#58]
odenwald.social ist der datenschutzfreundliche Microblogging-Service für alle Odenwälder:innen und alle, die den Odenwald mögen (All welcome).

URL: odenwald.social (also reachable via odw.social)
Open for Registration: yes
Region (Geo-Location): Michelstadt, Germany
Rules, Policies in place, conform with Convenant, VPS server, Daily backups

Thank you

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
