### ISSUE TITLE
Add rtk.social

### ISSUE THREAD

**Issue by padowa76** [jazmichaelking/mastodon-near-me#60]
Url: rtk.social
Description: Ein Server für alle Rheingauer, die Bergvölker aus dem Taunus und Umgebung. Jeder ist hier willkommen.
Location: 65529 Waldems 50.27596124868112, 8.345130385018761

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
