### ISSUE TITLE
Please add twittar.com.br

### ISSUE THREAD

**Issue by AlexSJ** [jazmichaelking/mastodon-near-me#63]
https://twittar.com.br

Geo: Brazil
Language Focus: Portuguese
Geo: -29.702394, -53.157343

tkx

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
