### ISSUE TITLE
Please Add Krems.social

### ISSUE THREAD

**Issue by servermaster1** [jazmichaelking/mastodon-near-me#66]
https://krems.social/

Description: Das Soziale Netzwerk für alle Kremser und Kremserinnen
Language Focus: German/Austrian
Geo: Krems an der Donau / Austria
Geo: 
- DD: lat:48.40921 lng:15.61415
- DMS: lat:48º24'33.16N ,lng:15º36'50.94 E
- geohash:u2e57k9uh4
- UTM:33U 545449.25435415 5361966.02410405

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
