### ISSUE TITLE
Add Mastodon.CL

### ISSUE THREAD

**Issue by pablo-barrera-yaksic** [jazmichaelking/mastodon-near-me#67]
https://mastodon.cl/

Description: Instancia de Mastodon en español con temática general orientado a la comunidad chilena 🇨🇱 
Language Focus: Español/Spanish
Geo: Santiago, Chile
Geo:
    lat:-33.4361704 lng:-70.6573578

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users for town/city or 100 active users for region/nation

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
