### ISSUE TITLE
please add vorarlberg.io

### ISSUE THREAD

**Issue by raieben** [jazmichaelking/mastodon-near-me#71]
https://vorarlberg.io/

Description: Das Soziale Netzwerk für alle VorarlbergInnen und Freunde des Ländles
Language Focus: German/Austrian
Geo: Feldkirch / Austria

DD: lat:47.2380 lng:9.5974
geohash:u0qudrkt79kn

Thx

**Comment by jazmichaelking** [comment]
Please consider registering on https://masto.town/ -  a register of regional instances
