### ISSUE TITLE
Add troet.fediverse.at

### ISSUE THREAD

**Issue by ilsd** [jazmichaelking/mastodon-near-me#75]
Server: https://troet.fediverse.at/home
Language: DE
Region: Austria (AT)
Centerpoint: https://www.openstreetmap.org/directions?engine=osrm_car&route=47.67648444221321,15.023803710937502&locale=en#map=8/47.67648444221321/15.023803710937502

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and please feel free to comment on this issue when your server hits 50 active users 

In the meantime please consider registering on https://masto.town/ - a register of regional instances
