### ISSUE TITLE
Add expressional.social

### ISSUE THREAD

**Issue by jippi** [jazmichaelking/mastodon-near-me#76]
Hosted in Copenhagen, Denmark

`55.62064495398267, 12.571284324970277` to be precise. 

About the server: https://expressional.social/docs/

**Comment by jazmichaelking** [comment]
This appears to be a general public server, not region or city specific, please describe the specific locality you are serving

**Comment by jippi** [comment]
It's primary focused on Denmark/Danes (>90%) but we do allow Swedes and Norwegians on there too, since languages are similar

**Comment by jazmichaelking** [comment]
added, thank you
