### ISSUE TITLE
Add wig.gl

### ISSUE THREAD

**Issue by WauloK** [jazmichaelking/mastodon-near-me#80]
wig.gl is hosted in Gladstone, QLD, Australia.

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users - in the meantime please consider registering on https://masto.town/ - a register of regional instances
