### ISSUE TITLE
Add imker.social

### ISSUE THREAD

**Issue by dirkheitzmann** [jazmichaelking/mastodon-near-me#81]
Service located in Bruchkoebel, Germany. 

Latitude of Bruchköbel | 50.1824581
Longitude of Bruchköbel | 8.9231185

Dedicated for German-speaking beekeepers.
Für deutschsprachige Imker und an Naturschutz Interessierte.

refer to https://meta.imker.social

**Comment by dirkheitzmann** [comment]
Language is German/Deutsch on https://imker.social

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and please feel free to comment on this issue when your server hits 50 active users

In the meantime please consider registering on https://masto.town/ - a register of regional instances
