### ISSUE TITLE
https://hoosier.social/

### ISSUE THREAD

**Issue by brianrlawson** [jazmichaelking/mastodon-near-me#84]
Specifically targeted to residents of Indiana.  The server's "About" specifically mentions the targeted audience and intention:

"Welcome to hoosier.social! This Mastodon server aims to support the interests and communication of Indiana residents. With respect to Hoosier Hospitality, we encourage civil discourse between our members and want to create a space that is open & accepting to all."

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and please feel free to comment on this issue when your server hits 50 active users

In the meantime please consider registering on https://masto.town/ - a register of regional instances; and also consider adopting the Mastodon Server Covenant for listing on the official directory at https://joinmastodon.org/covenant

**Comment by brianrlawson** [comment]
Hello! Following back up again. I believe that Hoosier Social now meets the criteria that kept us from the list before. We have well over 50 registers users, and over 50 active. We’re also listed on the joinmastodon.org site.
