### ISSUE TITLE
Add toots.nu

### ISSUE THREAD

**Issue by jenslj** [jazmichaelking/mastodon-near-me#87]
Add toots.nu 
Server language: Svenska (Swedish) or English
Location: Lund, Sweden

**Comment by jazmichaelking** [comment]
/added 

I can't tell if this is a Lund area service, or Sweden-wide. For a Sweden server I would normally add the marker above the country name, but I've added it to Lund as you described for now, let me know if you'd like to change it

(apologies for the delay, some issues with the map service)
