### ISSUE TITLE
https://hoosier.social/

### ISSUE THREAD

**Issue by brianrlawson** [jazmichaelking/mastodon-near-me#90]
Specifically targeted to residents of Indiana. The server's "About" specifically mentions the targeted audience and intention:

"Welcome to hoosier.social! This Mastodon server aims to support the interests and communication of Indiana residents. With respect to Hoosier Hospitality, we encourage civil discourse between our members and want to create a space that is open & accepting to all."

We have well over 50 registers users, and over 50 active. We’re also listed on the joinmastodon.org site.

**Comment by jazmichaelking** [comment]
added, thank you!
