### ISSUE TITLE
Location of norden.social is wrong

### ISSUE THREAD

**Issue by torgeros** [jazmichaelking/mastodon-near-me#98]
While the name of <https://norden.social> suggests that it might be from Norden, Germany, it's actually a general Northern German instance.

By [their imprint](https://norden.social/about) they are located in Bremen, Germany:

> norden.social
> Zum Sebaldsbrücker Bahnhof 1
> 28309 Bremen

OSM shows this address at `53.06237, 8.88309`.

**Comment by jazmichaelking** [comment]
Agreed it's a Northern Germany instance, working with the site logo which is Hamburg, I've moved the marker there.
