### ISSUE TITLE
add masto.es (Spanish) to list

### ISSUE THREAD

**Issue by santiagozky** [jazmichaelking/mastodon-near-me#99]
masto.es is a spanish speaking instance. The admin is based on Spain, but servers are in Germany.
from https://masto.es/about:

> masto.es es una comunidad de la red social Mastodon, abierta a cualquier persona cuyo idioma principal sea el español.
> El objetivo de masto.es es facilitar la interacción con hispanohablantes en Mastodon en un ambiente amable y seguro. El equipo de moderación velará siempre por el cumplimiento de las normas para lograrlo, pero también se ruega la colaboración de los miembros.

**Comment by jazmichaelking** [comment]
Añadido, gracias!
